# Generated by Django 5.1 on 2024-08-30 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('cep', models.IntegerField(max_length=8)),
                ('valorContaLuz', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ajusteTarifa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipoImovel', models.CharField(choices=[('R', 'Residencial'), ('E', 'Empresarial')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteWeb.usuario')),
            ],
        ),
    ]
