# Generated by Django 5.1 on 2024-08-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteWeb', '0002_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
